#!/bin/bash

# This commands need to be run after copying generated docs from `tigris docs` command to
# docs/sdkstools/cli/commands directory.

sed -i '/## tigris/d' docs/sdkstools/cli/commands/*.md
sed -i '/###### Auto generated by/d' docs/sdkstools/cli/commands/*.md

ls docs/sdkstools/cli/commands|sed -e 's/^tigris_//' -e 's/\.md//' -e 's/_/-/g'|sed 's+^+"sdkstools/cli/commands/+'|sed 's/$/",/'
